### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by julien-nc** [nextcloud/integration_slack#1]
First of all, this is very well done :+1: 

A few remarks:

- [x] Instead of saving the redirect URI, we could compute it in https://github.com/nextcloud/integration_slack/blob/main/lib/Controller/ConfigController.php#L196 . But I agree with you, it might be better to get it from the frontend as then we are sure it's the same as the one we sent in the `slack.com/oauth/v2/authorize` request.
- [x] Why do you save the redirect URI for each user? It could be saved as an app config value when setting the client ID/secret for example.
- [x] Nice screenshots, agent A
- [x] The Mattermost integration app uses an old method to load the files plugin script on `LoadAdditionalScriptsEvent`. Could you check how the `RenderReferenceEvent` event is handled in https://github.com/nextcloud/integration_openstreetmap and do something similar? It's registering a listener in Application::register (https://github.com/nextcloud/integration_openstreetmap/blob/main/lib/AppInfo/Application.php#L62) and you can get the current $userId in the listener.
- [x] Nice that you encrypt the client secret :+1: 
- [x] Most NC developers avoid trailing comments like https://github.com/nextcloud/integration_slack/blob/main/lib/Service/SlackAPIService.php#L216-L217 . I have nothing against it but I'm also avoiding them :grin: . As you wish.
- [x] The CHANGELOG is still the one from the Mattermost app
- [x] https://github.com/nextcloud/integration_slack/blob/main/lib/Service/SlackAPIService.php#L338 This syntax only works in Php >= 8.1 and this app supports NC 26 which supports Php 8.0.

**Comment by kyteinsky** [comment]
Redirect URI is now only computed and shown in the admin settings since Slack's page says: `If you pass a URL in an OAuth request, it must (partially) match one of the URLs you enter here.` in the OAuth settings. We do not pass it in any requests.

**Comment by julien-nc** [comment]
Do you mean that Slack will use the redirect URI that is authorized in the OAuth app settings if we don't pass any in the `oauth/v2/authorize`?
