### ISSUE TITLE
Setup the translation sync

### ISSUE THREAD

**Issue by julien-nc** [nextcloud/integration_slack#2]
Hey, here is the related doc: https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html?highlight=translation#setup-of-the-transifex-sync

**Comment by kyteinsky** [comment]
https://github.com/nextcloud/docker-ci/issues/561

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/integration_slack/commit/de54d1932d2bb95afd239f85d41af079c9de70d3
