### ISSUE TITLE
[enh] channel list must be searchable

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/integration_slack#7]
currently no search string can be entered

**Comment by ferdiga** [comment]
isn't a searchable drop down standard like in link sharing?
<img width="178" alt="20231003 173732 Files - Storage Share" src="https://github.com/nextcloud/integration_slack/assets/6248560/672ebef6-5690-49b5-9af1-d26173172c46">

**Comment by kyteinsky** [comment]
Hello, the search box/conversation selector should be searchable in the next release if it was not before. Yes, it is using the same component as in your screenshot.
